version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  namenode:
    image: apache/hadoop:3.3.6
    container_name: namenode
    hostname: namenode
    volumes:
      - namenode_data:/tmp/hadoop-root
    ports:
      - "9870:9870"
    command: ["hdfs", "namenode"]

  datanode:
    image: apache/hadoop:3.3.6
    container_name: datanode
    hostname: datanode
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    volumes:
      - datanode_data:/tmp/hadoop-root
    command: ["hdfs", "datanode"]

  hive-metastore:
    build: .
    container_name: hive-metastore
    hostname: hive-metastore
    depends_on:
      - mysql
      - namenode
      - datanode
    volumes:
      - namenode_data:/tmp/hadoop-root
    ports:
      - "9083:9083"
    command: ["/opt/hive/bin/hive", "--service", "metastore"]

  hive-server:
    build: .
    container_name: hive-server
    hostname: hive-server
    depends_on:
      - hive-metastore
    ports:
      - "10000:10000"
      - "10002:10002"
    command: ["/opt/hive/bin/hive", "--service", "hiveserver2"]

volumes:
  namenode_data:
  datanode_data:
